name: Continuous Integration

on: [ push, pull_request ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Code quality checks
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
          version: "latest"

      - name: MyPy type checking
        run: |
          poetry run mypy --strict

      - name: Test with pytest
        run: |
          poetry run pytest
